name: nyoba_modul_5
description: "ini merupakan project development kelompok 4"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  flutter_spinkit: ^5.2.0
  salomon_bottom_bar: ^3.3.2
  google_sign_in: ^6.3.0
  google_sign_in_web: ^0.12.4+4 # atau versi terkini
  flutter_facebook_auth: ^7.1.2
  firebase_storage: ^12.4.7
  image_picker: ^1.1.2
  lottie: ^3.3.1
  http: ^1.4.0
  google_fonts: ^6.2.1
  flashy_tab_bar2: ^0.0.10
  intro_slider: ^4.2.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.0+1
  cloudinary_dart: ^0.0.11
  flutter_dotenv: ^5.2.1
  image: ^4.5.4
  dio: ^5.8.0+1
  # flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  awesome_notifications: ^0.10.1
  connectivity_plus: ^6.1.4
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  place_picker_google: ^0.0.6 
  # firebase_auth: ^5.5.4
  google_maps_flutter: ^2.1.1 

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
    - assets/icon/sepeda.gif
    - assets/image/tambal_ban.jpg
    - assets/icon/sepeda.json
    - assets/icon/motor.png
    - assets/icon/truck.png
    - assets/icon/mobil.png
    - assets/icon/bicycle.png
    - assets/icon/lokasi.json
    - assets/icon/loading.json
    - assets/fonts/Hello-Botuna.ttf
    - assets/animations/loading.json
    - assets/animations/onboarding1.json
    - assets/animations/onboarding2.json
    - assets/animations/onboarding3.json
    - assets/animations/
    - .env

fonts:
  - family: Poppins
  # - family: HelloBotuna
    fonts:
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      # - asset: assets/fonts/Hello-Botuna.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
