// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiaOeNB9g77ZSzCSNLK2-lTjCycuRlUK0',
    appId: '1:475941342310:web:f4a72567a7ddc56160b1a7',
    messagingSenderId: '475941342310',
    projectId: 'modul-5-e2bb6',
    authDomain: 'modul-5-e2bb6.firebaseapp.com',
    storageBucket: 'modul-5-e2bb6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmX6Vur4Q3Q1oAD_qM6sY02YqargljGEY',
    appId: '1:475941342310:android:856f6c937dc0c7bf60b1a7',
    messagingSenderId: '475941342310',
    projectId: 'modul-5-e2bb6',
    storageBucket: 'modul-5-e2bb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfuqbfs22HKnsccxtR_z8Q_TxDyKSpp1Q',
    appId: '1:475941342310:ios:d339a912b8c8374560b1a7',
    messagingSenderId: '475941342310',
    projectId: 'modul-5-e2bb6',
    storageBucket: 'modul-5-e2bb6.firebasestorage.app',
    iosClientId: '475941342310-6c6m57pnckcaodkgig9je77ifpe75cpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.nyobaModul5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfuqbfs22HKnsccxtR_z8Q_TxDyKSpp1Q',
    appId: '1:475941342310:ios:d339a912b8c8374560b1a7',
    messagingSenderId: '475941342310',
    projectId: 'modul-5-e2bb6',
    storageBucket: 'modul-5-e2bb6.firebasestorage.app',
    iosClientId: '475941342310-6c6m57pnckcaodkgig9je77ifpe75cpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.nyobaModul5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiaOeNB9g77ZSzCSNLK2-lTjCycuRlUK0',
    appId: '1:475941342310:web:5086f9414ffd9d4c60b1a7',
    messagingSenderId: '475941342310',
    projectId: 'modul-5-e2bb6',
    authDomain: 'modul-5-e2bb6.firebaseapp.com',
    storageBucket: 'modul-5-e2bb6.firebasestorage.app',
  );

}